apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260515-200210-3x7d1tu9w9mu-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260515-200210-3x7d1tu9w9mu.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260515-200210-3x7d1tu9w9mu-service
            port:
              number: 80
